### ISSUE TITLE
Опишите подробнее.

### ISSUE THREAD

**Issue by andrey-ilyin** [JohnnyCatsvill/BEP#1]
https://github.com/JohnnyCatsvill/BEP/blob/43f0f500d08060dbff2d67482c7b59b377bff232/Lab1/Task2.txt#L3

**Comment by JohnnyCatsvill** [comment]
В файле php_is_a_server_scripting_language.php лежит заголовок который перенаправляет загрузку на сторонний сайт -> Location: http://fi2.php.net/manual/ru/

**Comment by andrey-ilyin** [comment]
Принято.
